version: '3.8'

services:
  drosophiladrone-real:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: drosophiladrone-real-px4:latest
    container_name: drosophiladrone_real_px4
    privileged: true
    network_mode: host
    volumes:
      - ..:/drosophiladrone
    environment:
      - HEADLESS=1
      - PX4_SYS_AUTOSTART=4001
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
